### PR TITLE
force update all libs

### PR DESCRIPTION
**Pull request by Luser0**
## Description

Updated libs to get rid of security warnings 

No affect on tests

{
  the tests are broken because of a type error
  
  i fixed that type error and ran a before and after with no change

  type error will be fixed in another PR
}

### CODE REVIEW

**Comment by Cliftonz** [comment]
@bedokuroff @gavinofla Could we get some help on closing this issue?

**Comment by MathiasGruber** [comment]
Also keen to see this merged

**Comment by zanemcca** [comment]
Can this get a review and merge by someone at pusher please @benw-pusher? We are having issues in production right now because jsonwebtoken is too out of date.

**Comment by klclee** [comment]
Hi guys, please can we get this merged? We be forced to move away from pusher if this anit released soon. Our IT dept have release warning to block our app. thank you

**Comment by operfildoluiz** [comment]
PLease, can we get it merged? It's a high risk vulnerabilty

**Comment by evgeniibreikin** [comment]
Just published this fix https://github.com/pusher/push-notifications-node/pull/73

**Pull request closed without merging**
